# Copyright (C) 2018 - 2020 MrYacha.
# This file is part of oAPI.


stages:
  - release


docker_branch:
  # Builds docker image with tag same as commited branch
  image: docker:latest
  stage: release
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com
  script:
    - docker build -t "$DOCKER_IMAGE" .
    - docker push "$DOCKER_IMAGE"
