# Copyright (C) 2018 - 2020 MrYacha.
# This file is part of oAPI.


stages:
  - release


docker_branch:
  # Builds docker image with tag same as commited branch
  image: docker:latest
  stage: release
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com
  script:
    - docker build -t "$DOCKER_IMAGE" .
    - docker push "$DOCKER_IMAGE"


docker_version:
  # Builds docker image with version tags
  image: docker:latest
  stage: release
  services:
    - docker:dind
  before_script:
    - apk add python3
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com
  script:
    - VERSION_FULL=$(python3 -c "import obot.version as version; print(version.version)")
    - VERSION_MAJOR=$(echo $VERSION_FULL | sed 's/\..*//')
    - TAGS="$VERSION_FULL $VERSION_MAJOR latest"

    - for tag in $TAGS; do
        DOCKER_IMAGE="$CI_REGISTRY_IMAGE:$tag";
        docker build -t "$DOCKER_IMAGE" .;
        docker push "$DOCKER_IMAGE";
      done
  only:
    - master
